"""
generation/report_generator.py

Responsible ONLY for:
- Reading execution.json and relevant evidence
- Sending ONE Gemini request for QA report generation
- Writing generated/reports/report.md

No test generation here. No pytest execution here. Report generation ONLY.
"""

import json
import logging
from pathlib import Path

from google import genai
from google.genai import types

from generation.config import Config

logger = logging.getLogger(__name__)

GENERATED_DIR = Path("generated")
REPORTS_DIR = GENERATED_DIR / "reports"
EXECUTION_JSON = REPORTS_DIR / "execution.json"
EVIDENCE_UI_DIR = Path("evidence/ui")
EVIDENCE_API_DIR = Path("evidence/api")


def _read_json(filepath: Path) -> dict:
    """Read and parse a JSON file."""
    if filepath.exists():
        return json.loads(filepath.read_text(encoding="utf-8"))
    return {}


def _read_file(filepath: Path) -> str:
    """Read a text file safely."""
    if filepath.exists():
        return filepath.read_text(encoding="utf-8")
    return ""


def _build_report_prompt(
    execution: dict,
    ui_summary: dict,
    api_summary: dict,
    spec: str,
) -> str:
    """
    Build the ONE Gemini prompt for QA report generation.
    """
    execution_json = json.dumps(execution, indent=2, default=str)

    # Summarize key evidence points
    ui_workflows = list(ui_summary.get("workflows", {}).keys())
    api_workflows = list(api_summary.get("workflows", {}).keys())

    # Extract failure details for report
    failures = [
        t for t in execution.get("tests", [])
        if t.get("status") in ("failed", "error")
    ]
    failure_details = json.dumps(failures, indent=2, default=str)

    passed = execution.get("passed", 0)
    failed = execution.get("failed", 0)
    skipped = execution.get("skipped", 0)
    total = execution.get("total", 0)
    duration = execution.get("duration_seconds", 0)

    prompt = f"""You are a senior QA Automation Engineer writing a professional QA execution report.

You have just run automated tests against the Restful Booker Platform.
Write a clear, factual, professional QA report based on the execution data provided.

=== EXECUTION DATA ===
{execution_json}

=== UI WORKFLOWS EXPLORED ===
{ui_workflows}

=== API WORKFLOWS EXPLORED ===
{api_workflows}

=== FAILURE DETAILS ===
{failure_details}

=== SPECIFICATION CONTEXT ===
{spec[:3000]}

=== REPORT REQUIREMENTS ===

Write the report in Markdown format with these sections:

# QA Automation Execution Report
## Restful Booker Platform

---

## Executive Summary
Brief 2-3 sentence overview of the test run outcome.
State clearly: how many tests ran, how many passed/failed, and overall quality signal.

---

## Test Execution Summary

| Metric | Value |
|--------|-------|
| Total Tests | {total} |
| Passed | {passed} |
| Failed | {failed} |
| Skipped | {skipped} |
| Duration | {duration}s |
| Pass Rate | calculated |

---

## UI Test Results

List each UI test with its result status.
Group by: Home, Navigation, Rooms, Booking, Admin.

---

## API Test Results

List each API test with its result status.
Group by: Authentication, Rooms API, Bookings API.

---

## Failure Analysis

For each failed test:
- **Test:** test name
- **Status:** failed/error
- **Observed Error:** (exact error message from execution data — this is FACT)
- **Likely Technical Cause:** (your inference — clearly mark as INFERENCE)
- **Suggested Investigation:** actionable next step

If no failures: state "All tests passed."

IMPORTANT: Clearly distinguish:
- **[FACT]** — directly from execution data
- **[INFERENCE]** — your technical analysis

---

## Coverage Summary

Which workflows were covered:
- UI workflows tested
- API workflows tested
- Workflows NOT covered

---

## Recommendations

2-5 actionable QA recommendations based ONLY on the observed test results.
Do not invent issues that are not evidenced in the execution data.

---

## Test Artifacts

| Artifact | Path |
|----------|------|
| HTML Report | generated/reports/html/report.html |
| JUnit XML | generated/reports/junit.xml |
| Execution JSON | generated/reports/execution.json |

---

*Report generated by AI QA Automation Framework*
*Based on actual execution evidence — AI inferences are explicitly marked.*

Generate the complete report now in Markdown format.
"""

    return prompt


def generate_report(config: Config) -> str:
    """
    Generate the QA report using Gemini.

    Returns the path to the generated report.md file.
    """
    # Load execution results
    execution = _read_json(EXECUTION_JSON)
    if not execution:
        logger.warning("execution.json not found — generating minimal report")
        execution = {"total": 0, "passed": 0, "failed": 0, "skipped": 0, "tests": []}

    # Load evidence summaries
    ui_summary = _read_json(EVIDENCE_UI_DIR / "ui_evidence_summary.json")
    api_summary = _read_json(EVIDENCE_API_DIR / "api_evidence_summary.json")

    # Load spec for context
    spec = _read_file(Path("spec.md"))

    # Build prompt
    prompt = _build_report_prompt(execution, ui_summary, api_summary, spec)

    # Configure Gemini (new google.genai SDK v2.x)
    client = genai.Client(api_key=config.gemini_api_key)

    logger.info(f"  [REPORT] Sending report request to Gemini ({config.gemini_model})...")

    # Send the ONE report generation request
    response = client.models.generate_content(
        model=config.gemini_model,
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.3,
            max_output_tokens=8192,
        ),
    )

    report_content = response.text
    logger.info(f"  [REPORT] Report generated ({len(report_content)} characters)")

    # Write report.md
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / "report.md"
    report_path.write_text(report_content, encoding="utf-8")

    logger.info(f"  [REPORT] Report saved: {report_path}")
    return str(report_path)
